import localFont from "next/font/local";
import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";



const Cormorant = localFont({
  src: "./fonts/CormorantGaramond-Regular.ttf",
  variable: "--cormorant",
  weight: "400",
})

const Lato = localFont({
  src: "./fonts/Lato-Regular.ttf",
  variable: "--lato",
  weight: "400",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body
        className={`${Cormorant.variable} ${Lato.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
