import localFont from "next/font/local";
import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";






const Libre = localFont({
  src: "./fonts/LibreCaslonDisplay-Regular.ttf",
  variable: "--libre",
  weight: "400",
})

const Poppins= localFont({
  src: "./fonts/Poppins-Regular.ttf",
  variable: "--Poppins",
  weight: "400",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body
        className={` ${Libre.variable} ${Poppins.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
